package swp391.com.backend.jpa.pojo.blog;

public enum BlogCategory {
    STI_OVERVIEW,
    TESTING_AND_DIAGNOSIS,
    PREVENTION,
    TREATMENT,
    SYMPTOMS_AND_SIGNS,
    LIVING_WITH_STI,
    PARTNER_NOTIFICATION,
    MYTHS_AND_FACTS,
    RESOURCES_AND_SUPPORT,
    VACCINATION,
    RISK_FACTORS,
    YOUTH_EDUCATION,
    PREGNANCY_AND_STI,
    LGBTQ_HEALTH,
    POLICY_AND_ADVOCACY
}
